apiVersion: v1
kind: Namespace
metadata:
name: data
---
apiVersion: apps/v1
kind: Deployment
metadata:
name: redis-deployment
namespace: data
spec:
replicas: 1
selector:
 matchLabels:
   app: redis
template:
 metadata:
   labels:
     app: redis
 spec:
   containers:
   - name: redis
     image: redis:latest
     env:
     - name: REDIS_PASSWORD
       valueFrom:
         secretKeyRef:
           name: redis-secret
           key: redis-password
     ports:
     - containerPort: 12345
     volumeMounts:
     - name: redis-data
       mountPath: /data/redis
   volumes:
   - name: redis-data
     persistentVolumeClaim:
       claimName: redis-pvc
   restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
name: redis-service
namespace: data
spec:
selector:
 app: redis
ports:
- protocol: TCP
 port: 12346
 targetPort: 12345
type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
name: redis-pvc
namespace: data
spec:
accessModes:
- ReadWriteOnce
resources:
 requests:
   storage: 1Gi
storageClassName: fast-sc
---
apiVersion: v1
kind: Secret
metadata:
name: redis-secret
namespace: data
data:
redis-password: UWFpc3MuMTg3MTMxMw==
